{"uuid": "1921156a-131c-49aa-9123-8787e6102915", "children": ["6438a70f-d90b-4206-bfdb-21e7bfec9129"], "befores": [{"name": "data_cleaning", "status": "passed", "start": 1703767431957, "stop": 1703767436054}], "afters": [{"name": "data_cleaning::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'ConnectMysql' object has no attribute 'conn'\n", "trace": "  File \"F:\\python3.11.2\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"F:\\python3.11.2\\Lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\webuiauto\\conftest.py\", line 18, in data_cleaning\n    conn.delete(sql)\n  File \"D:\\webuiauto\\util_tools\\connectMysql.py\", line 67, in delete\n    self.close()\n  File \"D:\\webuiauto\\util_tools\\connectMysql.py\", line 29, in close\n    if self.conn and self.cursor:\n       ^^^^^^^^^\n"}, "start": 1703767449728, "stop": 1703767449733}], "start": 1703767431957, "stop": 1703767449733}